runtime: nodejs10

env_variables:
  COOL: 'cool'

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /intro\.jpg
  static_files: static/intro.jpg
  upload: static/intro.jpg

- url: /static
  static_dir: static/static

# - url: /.*
#   static_files: static/index.html
#   upload: static/index.html

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto